networks:
  kafka-and-dotnet:
    driver: bridge
    
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - kafka-and-dotnet
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=mysecretpassword
      - ALLOW_PLAINTEXT_LISTENER=true
    ports:
      - "9092:9092"
      - "9094:9094"
    expose:
      - 9094
    healthcheck:
      test: kafka-topics.sh --bootstrap-server=kafka:9092 --list || exit 1
      interval: 1s
      timeout: 10s
      retries: 60
    volumes:
     - kafka:/bitnami/kafka
     
  karapace-sr:
    depends_on:
      kafka:
        condition: service_healthy
    image: ghcr.io/aiven-open/karapace:latest
    command: "/opt/karapace/start.sh registry"
    container_name: karapace-sr
    networks:
      - kafka-and-dotnet
    environment:
      - KARAPACE_BOOTSTRAP_URI=kafka:9092
      - KARAPACE_LOG_HANDLER=stdout
      - KARAPACE_LOG_LEVEL=INFO
      - KARAPACE_PORT=8081
      - KARAPACE_HOST=0.0.0.0
      - KARAPACE_CLIENT_ID=karapace
      - KARAPACE_GROUP_ID=karapace-registry
      - KARAPACE_KARAPACE_REGISTRY=true
    ports:
      - "8081:8081"
    expose:
      - 8081

  kafka-ui:
    depends_on:
      kafka:
        condition: service_healthy
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-and-dotnet
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://karapace-sr:8081/
    ports:
      - "8080:8080"
    expose:
      - 8080
    
volumes:
  kafka:
    name: kafka-and-dotnet
  
